import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const code=ts.transpileModule(await readFile('app/optimistic-like.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {updateLikeOptimistically}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
let resolveSave,rejectSave;
const pending=()=>new Promise((resolve,reject)=>{resolveSave=resolve;rejectSave=reject});
let states=[];
const result=updateLikeOptimistically({liked:false,likeCount:3},state=>states.push(state),liked=>{assert.equal(liked,true);return pending()});
assert.deepEqual(states,[{liked:true,likeCount:4}], 'Like must render before network completion');
resolveSave({liked:true,likeCount:5});await result;
assert.deepEqual(states.at(-1),{liked:true,likeCount:5},'Use authoritative count including other users');
states=[];
const removal=updateLikeOptimistically({liked:true,likeCount:5},state=>states.push(state),liked=>{assert.equal(liked,false);return pending()});
assert.deepEqual(states,[{liked:false,likeCount:4}]);
rejectSave(Error('offline'));await assert.rejects(removal,/offline/);
assert.deepEqual(states.at(-1),{liked:true,likeCount:5},'Roll back failed removal');
states=[];
await assert.rejects(updateLikeOptimistically({liked:false,likeCount:0},state=>states.push(state),async()=>{throw Error('HTTP 500')}));
assert.deepEqual(states,[{liked:true,likeCount:1},{liked:false,likeCount:0}]);
states=[];
await updateLikeOptimistically({liked:true,likeCount:0},state=>states.push(state),async()=>({liked:false,likeCount:0}));
assert.equal(states[0].likeCount,0,'Never render a negative count');
console.log('Optimistic like checks passed: immediate add/remove, server reconciliation, network/HTTP rollback, nonnegative count.');
