'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Anchor,Fish,MapPin,Plus,Search,CalendarDays,Trash2,Pencil,Waves,Camera,X,Heart,LogOut} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {compressPhoto} from './photo-compression';
import CatchDateField from './catch-date-field';
import {validateCatch,type CatchFieldErrors} from './catch-validation';
import SeasonalHero from './seasonal-hero';
import DemoControls from './demo-controls';
import DiscoveryPanel from './discovery-panel';
import {type Period} from './discovery';
import {updateLikeOptimistically} from './optimistic-like';
import ProfileDialog,{Avatar,type Profile} from './profile-dialog';
import {toast,Toaster} from 'sonner';

type FishLine={id?:number;species:string;count:number;length:number|null};
type FishForm={id?:number;species:string;count:number|string;length:number|string|null};
type CatchPhoto={id:number;species:string};
type Entry={id:number;date:string;location:string;fish:FishLine[];photos:CatchPhoto[];featured_photo_id:number|null;method:string;memo:string;created_at:string;owner_id:string;authorName:string;likeCount:number;liked:boolean};
type PendingPhoto={key:string;file:File;species:string;preview:string};
const makeEmpty=()=>({date:new Date().toLocaleDateString('sv-SE'),location:'',fish:[{species:'',count:1,length:''}] as FishForm[],method:'',memo:''});

export default function FishingLog({canManageDemo=false,userId,initialName,signOutPath,signInPath}:{canManageDemo?:boolean;userId:string;initialName:string;signOutPath:string;signInPath:string}){
 const [profile,setProfile]=useState<Profile>({userId,displayName:initialName,bio:''}),[viewProfile,setViewProfile]=useState<Profile|null>(null),[scope,setScope]=useState('all'),[signedOut,setSignedOut]=useState(false),[busyLikes,setBusyLikes]=useState<Set<number>>(new Set());
 const [period,setPeriod]=useState<Period>(7),[now,setNow]=useState(()=>new Date()),[compressing,setCompressing]=useState(false);
 const [items,setItems]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<number|null>(null),[form,setForm]=useState(makeEmpty),[query,setQuery]=useState(''),[speciesFilter,setSpeciesFilter]=useState('すべて'),[saving,setSaving]=useState(false);
 const [files,setFiles]=useState<PendingPhoto[]>([]),[existingPhotos,setExistingPhotos]=useState<CatchPhoto[]>([]),[featured,setFeatured]=useState<number|string|null>(null);
 const [fieldErrors,setFieldErrors]=useState<CatchFieldErrors>({}),[validated,setValidated]=useState(false);
 function resetValidation(){setFieldErrors({});setValidated(false)}
 function revalidate(){if(validated)setFieldErrors(validateCatch(form).errors)}
 function fieldProps(key:string){return {'aria-invalid':!!fieldErrors[key],'aria-describedby':fieldErrors[key]?`catch-error-${key}`:undefined,onBlur:revalidate}}
 function fieldError(key:string){return fieldErrors[key]?<span className="field-error" id={`catch-error-${key}`}>{fieldErrors[key]}</span>:null}
 const photoTask=useRef(0),photoBusy=useRef(false),listHeading=useRef<HTMLHeadingElement>(null),likeLocks=useRef(new Set<number>()),leaving=useRef(false),refreshVersion=useRef(0);

 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60_000);return()=>clearInterval(timer)},[]);
 function cancelPhotoTask(){photoTask.current++;photoBusy.current=false;setCompressing(false)}
 function clearPending(){setFiles(current=>{for(const photo of current)URL.revokeObjectURL(photo.preview);return []})}
 function selectRankedSpecies(name:string){setQuery('');setSpeciesFilter(name);listHeading.current?.focus({preventScroll:true});listHeading.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
 function leave(path:string){cancelPhotoTask();clearPending();leaving.current=true;setItems([]);setViewProfile(null);setOpen(false);setSignedOut(true);window.open(path,'_top')}
 async function apiFetch(input:string,init?:RequestInit){if(leaving.current)throw Error('ログイン画面へ移動しています。');const response=await fetch(input,{...init,cache:'no-store'});if(response.status===401){leave(signInPath);throw Error('ログインしてください。')}return response}
 async function logout(){try{const r=await apiFetch(signOutPath,{method:'POST'});if(!r.ok)throw Error();leave('/')}catch{if(!leaving.current)toast.error('ログアウトできませんでした。もう一度お試しください。')}}

 useEffect(()=>{
  apiFetch('/api/profile').then(async r=>{if(!r.ok)throw Error();const p=await r.json() as Profile;if(!leaving.current)setProfile(p)}).catch(()=>toast.error('プロフィールを読み込めませんでした。'));
  const hide=()=>{document.body.style.visibility='hidden'},show=(e:PageTransitionEvent)=>{if(e.persisted)window.location.reload();else document.body.style.visibility='visible'};
  window.addEventListener('pagehide',hide);window.addEventListener('pageshow',show);return()=>{window.removeEventListener('pagehide',hide);window.removeEventListener('pageshow',show)};
 },[]);
 async function showProfile(id:string){try{const r=await apiFetch('/api/profiles/'+encodeURIComponent(id));if(!r.ok)throw Error();const p=await r.json() as Profile;if(!leaving.current)setViewProfile(p)}catch{toast.error('プロフィールを読み込めませんでした。')}}
 async function saveProfile(displayName:string,bio:string){const r=await apiFetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName,bio})}),value=await r.json() as Profile&{error?:string};if(!r.ok)throw Error(value.error||'保存できませんでした。');setProfile(value);setItems(current=>current.map(x=>x.owner_id===userId?{...x,authorName:value.displayName}:x));toast.success('プロフィールを保存しました')}

 async function like(x:Entry){
  if(likeLocks.current.has(x.id)||leaving.current)return;likeLocks.current.add(x.id);setBusyLikes(new Set(likeLocks.current));refreshVersion.current++;
  const publish=(state:{liked:boolean;likeCount:number})=>{refreshVersion.current++;if(!leaving.current)setItems(current=>current.map(item=>item.id===x.id?{...item,...state}:item))};
  try{await updateLikeOptimistically({liked:x.liked,likeCount:x.likeCount},publish,async liked=>{const r=await apiFetch(`/api/catches/${x.id}/like`,{method:liked?'PUT':'DELETE'});if(!r.ok)throw Error();return await r.json() as {liked:boolean;likeCount:number}})}
  catch{if(!leaving.current){toast.error('いいねを保存できなかったため、表示を戻しました。');likeLocks.current.delete(x.id);await refresh()}}
  finally{likeLocks.current.delete(x.id);setBusyLikes(new Set(likeLocks.current))}
 }
 async function refresh(){const version=++refreshVersion.current;try{const r=await apiFetch('/api/catches');if(!r.ok)throw Error();const rows=await r.json() as Entry[];if(!leaving.current&&version===refreshVersion.current){setItems(current=>rows.map(row=>likeLocks.current.has(row.id)?{...row,liked:current.find(x=>x.id===row.id)?.liked??row.liked,likeCount:current.find(x=>x.id===row.id)?.likeCount??row.likeCount}:row));setError('')}}catch{setError('記録を読み込めませんでした。時間をおいて再試行してください。')}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'create_catch_record',title:'釣果を記録',description:'釣行日、場所、魚種、匹数を保存して一覧を更新します。',inputSchema:{type:'object',properties:{date:{type:'string'},location:{type:'string'},species:{type:'string'},count:{type:'integer'},length:{type:'number'},method:{type:'string'},memo:{type:'string'}},required:['date','location','species','count'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const response=await apiFetch('/api/catches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),result=await response.json() as {id:number,error?:string};if(!response.ok)throw Error(result.error||'保存できませんでした');await refresh();return {saved:true,id:result.id}}},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort()},[]);

 const scoped=useMemo(()=>scope==='mine'?items.filter(x=>x.owner_id===userId):items,[scope,items,userId]);
 const species=useMemo(()=>['すべて',...new Set(scoped.flatMap(x=>x.fish.map(f=>f.species)))],[scoped]);
 const filtered=scoped.filter(x=>(speciesFilter==='すべて'||x.fish.some(f=>f.species===speciesFilter))&&`${x.location} ${x.fish.map(f=>f.species).join(' ')} ${x.method} ${x.memo}`.toLowerCase().includes(query.toLowerCase()));
 const total=scoped.reduce((n,x)=>n+x.fish.reduce((sum,f)=>sum+Number(f.count),0),0),unique=new Set(scoped.flatMap(x=>x.fish.map(f=>f.species))).size;

 function startEdit(x:Entry){resetValidation();cancelPhotoTask();clearPending();setEditing(x.id);setExistingPhotos(x.photos);setFeatured(x.featured_photo_id);setForm({date:x.date,location:x.location,fish:x.fish.map(f=>({...f,length:f.length?.toString()??''})),method:x.method,memo:x.memo});setOpen(true)}
 function startNew(){resetValidation();cancelPhotoTask();clearPending();setEditing(null);setExistingPhotos([]);setFeatured(null);setForm(makeEmpty());setOpen(true)}
 function updateFish(index:number,patch:Partial<FishForm>){const before=form.fish[index].species,next=form.fish.map((fish,i)=>i===index?{...fish,...patch}:fish);setForm({...form,fish:next});if(typeof patch.species==='string'&&before&&before!==patch.species){setExistingPhotos(current=>current.map(p=>p.species===before?{...p,species:patch.species as string}:p));setFiles(current=>current.map(p=>p.species===before?{...p,species:patch.species as string}:p))}}
 function addFish(){if(form.fish.length>=20)return toast.error('魚種は20種類まで登録できます。');const next={...form,fish:[...form.fish,{species:'',count:1,length:''}]};setForm(next);if(validated)setFieldErrors(validateCatch(next).errors)}
 function removeFish(index:number){if(form.fish.length===1)return toast.error('魚種を1つ以上登録してください。');const target=form.fish[index].species;if(target&&(existingPhotos.some(p=>p.species===target)||files.some(p=>p.species===target)))return toast.error('この魚種の写真を別の魚種へ変更してから削除してください。');const next={...form,fish:form.fish.filter((_,i)=>i!==index)};setForm(next);if(validated)setFieldErrors(validateCatch(next).errors)}
 const fishNames=form.fish.map(f=>f.species.trim()).filter(Boolean);

 async function submit(e:React.FormEvent){
  e.preventDefault();if(photoBusy.current||saving)return;const checked=validateCatch(form);setValidated(true);setFieldErrors(checked.errors);if(!checked.success)return;if((existingPhotos.length||files.length)&&featured===null)return toast.error('代表写真を選んでください。');
  setSaving(true);try{const current=editing?items.find(x=>x.id===editing):null,payload={...checked.data,photoAssignments:existingPhotos.map(p=>({photoId:p.id,species:p.species.trim()})),featuredPhotoId:typeof featured==='number'?featured:current?.featured_photo_id??null};const r=await apiFetch('/api/catches'+(editing?`/${editing}`:''),{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await r.json() as {id?:number,error?:string};if(!r.ok)throw Error(result.error||'保存できませんでした');const id=editing||result.id;let failed=0;for(const photo of files){const body=new FormData();body.append('photo',photo.file);body.append('species',photo.species.trim());body.append('featured',String(featured===photo.key));try{const upload=await apiFetch(`/api/catches/${id}/photos`,{method:'POST',body});if(!upload.ok)failed++}catch{failed++}}clearPending();setOpen(false);await refresh();if(failed)toast.error(`記録は保存しましたが、写真${failed}枚を追加できませんでした。編集画面から再追加してください。`);else toast.success(editing?'記録を更新しました':'釣果を記録しました')}
  catch(e){toast.error(e instanceof Error?e.message:'保存できませんでした')}finally{setSaving(false)}
 }
 async function choosePhotos(e:React.ChangeEvent<HTMLInputElement>){
  const selected=Array.from(e.target.files||[]);e.target.value='';if(photoBusy.current||saving||!selected.length)return;
  if(selected.length+files.length+existingPhotos.length>6)return toast.error('写真は1件につき6枚までです。');if(selected.some(f=>f.size>8*1024*1024||f.size===0))return toast.error('写真は1枚8MB以下にしてください。');const defaultSpecies=fishNames[0];if(!defaultSpecies)return toast.error('先に魚種を入力してください。');
  const task=++photoTask.current;photoBusy.current=true;setCompressing(true);try{const compressed:PendingPhoto[]=[];for(const file of selected){const ready=await compressPhoto(file),key=crypto.randomUUID();compressed.push({key,file:ready,species:defaultSpecies,preview:URL.createObjectURL(ready)});if(task!==photoTask.current||leaving.current)return}if(featured===null&&compressed.length)setFeatured(compressed[0].key);setFiles(current=>[...current,...compressed])}catch(error){if(task===photoTask.current&&!leaving.current)toast.error(error instanceof Error?error.message:'写真を圧縮できませんでした。')}finally{if(task===photoTask.current){photoBusy.current=false;setCompressing(false)}}
 }
 function removePending(key:string){setFiles(current=>{const target=current.find(p=>p.key===key);if(target)URL.revokeObjectURL(target.preview);const next=current.filter(p=>p.key!==key);if(featured===key)setFeatured(existingPhotos[0]?.id??next[0]?.key??null);return next})}
 async function removePhoto(photoId:number){if(!editing||!confirm('この写真を削除しますか？'))return;try{const r=await apiFetch(`/api/catches/${editing}/photos/${photoId}`,{method:'DELETE'});if(!r.ok)throw Error();const next=existingPhotos.filter(p=>p.id!==photoId);setExistingPhotos(next);if(featured===photoId)setFeatured(next[0]?.id??files[0]?.key??null);await refresh();toast.success('写真を削除しました')}catch{toast.error('写真を削除できませんでした')}}
 async function remove(x:Entry){const names=x.fish.map(f=>f.species).join('・');if(!confirm(`${x.date}の${names}の記録を削除しますか？`))return;try{const r=await apiFetch(`/api/catches/${x.id}`,{method:'DELETE'});if(!r.ok)throw Error();await refresh();toast.success('記録を削除しました')}catch{toast.error('削除できませんでした')}}
 if(signedOut)return <div className="empty" role="status">ログイン画面へ移動しています…</div>;

 return <div className="app-shell"><Toaster position="top-center" richColors/>
  <header className="topbar"><div className="brand"><span className="brand-mark"><Waves size={23}/></span><span>釣果ノート</span></div><nav className="account-nav" aria-label="アカウント"><button className="profile-button" onClick={()=>showProfile(userId)}><Avatar name={profile.displayName}/><span>{profile.displayName}</span></button><a href={signOutPath} target="_top" onClick={e=>{e.preventDefault();void logout()}}><LogOut size={17}/><span>ログアウト</span></a></nav></header>
  <main><SeasonalHero onRecord={startNew} onView={()=>{setQuery('');setSpeciesFilter('すべて');listHeading.current?.focus({preventScroll:true});listHeading.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}}/><div className="container">
   <Dialog open={open} onOpenChange={value=>{if(saving)return;if(!value)cancelPhotoTask();setOpen(value)}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{editing?'記録を編集':'新しい釣果を記録'}</DialogTitle></DialogHeader>
    <form noValidate onSubmit={submit} className="entry-form"><p className="required-note">※は必須項目です</p>{fieldError('form')}<div className="form-grid"><CatchDateField value={form.date} error={fieldErrors.date} onBlur={revalidate} onChange={date=>setForm(current=>({...current,date}))}/><label><span className="required-field-label">場所 ※</span><Input {...fieldProps('location')} placeholder="例：三浦海岸" required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/>{fieldError('location')}</label></div>
     <fieldset className="fish-editor"><legend>釣った魚</legend>{form.fish.map((fish,index)=><div className="fish-row" key={index}><label><span className="required-field-label">魚種 ※</span><Input {...fieldProps(`fish.${index}.species`)} placeholder="例：シロギス" required value={fish.species} onChange={e=>updateFish(index,{species:e.target.value})}/>{fieldError(`fish.${index}.species`)}</label><label><span className="required-field-label">匹数 ※</span><Input {...fieldProps(`fish.${index}.count`)} type="number" min="1" max="9999" required value={fish.count} onChange={e=>updateFish(index,{count:e.target.value})}/>{fieldError(`fish.${index}.count`)}</label><label>最大サイズ（cm）<Input {...fieldProps(`fish.${index}.length`)} type="number" min="0" max="999" step="0.1" placeholder="任意" value={fish.length??''} onChange={e=>updateFish(index,{length:e.target.value})}/>{fieldError(`fish.${index}.length`)}</label><button type="button" className="fish-remove" aria-label={`${fish.species||`${index+1}番目の魚種`}を削除`} onClick={()=>removeFish(index)} disabled={form.fish.length===1}><Trash2 size={17}/></button></div>)}{fieldError('fish')}<Button type="button" variant="outline" onClick={addFish}><Plus size={16}/>魚種を追加</Button></fieldset>
     <label>釣り方・仕掛け<Input {...fieldProps('method')} placeholder="例：ちょい投げ、6号" value={form.method} onChange={e=>setForm({...form,method:e.target.value})}/>{fieldError('method')}</label><label>メモ<textarea {...fieldProps('memo')} placeholder="天気、潮、釣れた距離など" value={form.memo} onChange={e=>setForm({...form,memo:e.target.value})}/>{fieldError('memo')}</label>
     <div className="photo-field"><span className="photo-label">釣った魚の写真（最大6枚・1枚8MBまで）</span><p className="photo-help">各写真の魚種を選び、最近の釣果に表示する代表写真を1枚選んでください。</p>
      {(existingPhotos.length>0||files.length>0)&&<div className="photo-assignment-grid">{existingPhotos.map(photo=><div className="photo-assignment" key={photo.id}><img src={`/api/photos/${photo.id}`} alt={`${photo.species}の登録済み写真`}/><label>魚種<select value={photo.species} onChange={e=>setExistingPhotos(current=>current.map(p=>p.id===photo.id?{...p,species:e.target.value}:p))}>{fishNames.map(name=><option key={name}>{name}</option>)}</select></label><label className="featured-choice"><input type="radio" name="featured-photo" checked={featured===photo.id} onChange={()=>setFeatured(photo.id)}/>代表写真</label><button type="button" aria-label="この写真を削除" onClick={()=>removePhoto(photo.id)}><X size={17}/></button></div>)}{files.map(photo=><div className="photo-assignment" key={photo.key}><img src={photo.preview} alt={`${photo.species}の追加予定写真`}/><label>魚種<select value={photo.species} onChange={e=>setFiles(current=>current.map(p=>p.key===photo.key?{...p,species:e.target.value}:p))}>{fishNames.map(name=><option key={name}>{name}</option>)}</select></label><label className="featured-choice"><input type="radio" name="featured-photo" checked={featured===photo.key} onChange={()=>setFeatured(photo.key)}/>代表写真</label><button type="button" aria-label={`${photo.file.name}の選択を解除`} onClick={()=>removePending(photo.key)}><X size={17}/></button></div>)}</div>}
      <label className="photo-picker"><Camera size={20}/><span>{compressing?'写真を圧縮中…':'写真を撮る・選ぶ'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple disabled={compressing||saving} onChange={choosePhotos} aria-label="写真を選択"/></label><p role="status">{compressing?'写真を圧縮しています…':'写真はアップロード前に自動圧縮します。'}</p>
     </div><Button disabled={saving||compressing} type="submit" className="save-button">{compressing?'写真を圧縮中…':saving?'保存中…':'保存する'}</Button>
    </form></DialogContent></Dialog>
  <Tabs value={scope} onValueChange={value=>{setScope(value);setSpeciesFilter('すべて');setQuery('')}} className="scope-tabs"><TabsList aria-label="釣果の表示範囲"><TabsTrigger value="all">みんなの釣果</TabsTrigger><TabsTrigger value="mine">自分の釣果</TabsTrigger></TabsList></Tabs>
  {scope==='all'?(!loading&&!error?<DiscoveryPanel items={items} days={period} onDays={setPeriod} now={now} onSpecies={selectRankedSpecies} onProfile={showProfile} onLike={like} busyLikes={busyLikes}/>:<div className="discovery-loading" role="status">{loading?'最近の釣果を読み込み中…':'最近の釣果を読み込めませんでした。'}</div>):<section className="stats" aria-label="釣果の集計"><div><span className="stat-icon"><CalendarDays size={22}/></span><p>釣行記録</p><strong>{scoped.length}<small>件</small></strong></div><div><span className="stat-icon"><Fish size={22}/></span><p>釣った魚</p><strong>{total}<small>匹</small></strong></div><div><span className="stat-icon"><Anchor size={22}/></span><p>魚種</p><strong>{unique}<small>種類</small></strong></div></section>}
  <section className="log-section"><div className="section-heading"><div><p className="eyebrow">{scope==='all'?'ALL RECORDS':'YOUR RECORDS'}</p><h2 ref={listHeading} tabIndex={-1}>釣行一覧</h2></div><span className="result-count">{filtered.length} 件の記録</span></div><div className="filters"><label className="search"><Search size={18}/><input aria-label="記録を検索" placeholder="場所・魚種・メモを検索" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="魚種で絞り込み" value={speciesFilter} onChange={e=>setSpeciesFilter(e.target.value)}>{species.map(s=><option key={s}>{s}</option>)}</select></div>
   {error?<div className="empty"><p>{error}</p><Button variant="outline" onClick={refresh}>再試行</Button></div>:loading?<div className="empty">読み込み中…</div>:filtered.length===0?<div className="empty"><span className="empty-icon"><Fish size={34}/></span><h3>{scoped.length?'該当する記録がありません':'最初の釣果を記録しましょう'}</h3><p>{scoped.length?'検索条件を変えてみてください。':'釣行日、場所、魚種を残しておくと、次の釣行にも役立ちます。'}</p>{!scoped.length&&<Button onClick={startNew} className="add-button"><Plus size={17}/>釣果を記録</Button>}</div>:<div className="cards">{filtered.map(x=><article className="catch-card" key={x.id}><div className="card-main"><div className="date-badge"><strong>{new Date(x.date+'T00:00:00').getDate()}</strong><span>{new Date(x.date+'T00:00:00').toLocaleDateString('ja-JP',{year:'numeric',month:'short'})}</span></div><div className="catch-info"><button className="author-button" onClick={()=>showProfile(x.owner_id)}><Avatar name={x.authorName}/><span>{x.authorName}</span></button><div className="catch-fish-list">{x.fish.map(f=><div className="catch-title" key={f.species}><h3>{f.species}</h3><span className="count-badge">{f.count} 匹</span>{f.length!=null&&<span className="fish-length">最大 {f.length} cm</span>}</div>)}</div><p className="place"><MapPin size={16}/>{x.location}</p>{x.method&&<p className="details">{x.method}</p>}{x.memo&&<p className="memo">{x.memo}</p>}{x.photos.length>0&&<div className="photo-grid card-photos">{x.photos.map(photo=><a href={`/api/photos/${photo.id}`} target="_blank" rel="noopener noreferrer" key={photo.id} aria-label={`${photo.species}の写真を開く`}><img src={`/api/photos/${photo.id}`} alt={`${photo.species}の釣果写真`} loading="lazy"/><span>{photo.species}</span></a>)}</div>}</div></div><div className="card-actions"><button className={`like-button ${x.liked?'is-liked':''}`} aria-label={x.liked?'いいねを取り消す':'いいね'} aria-pressed={x.liked} disabled={busyLikes.has(x.id)} onClick={()=>like(x)}><Heart size={19} fill={x.liked?'currentColor':'none'}/><span>{x.likeCount}</span></button>{x.owner_id===userId&&<><button aria-label="釣果を編集" onClick={()=>startEdit(x)}><Pencil size={17}/></button><button aria-label="釣果を削除" onClick={()=>remove(x)}><Trash2 size={17}/></button></>}</div></article>)}</div>}
  </section>{canManageDemo&&<DemoControls onChange={refresh}/>}</div></main>
  {viewProfile&&<ProfileDialog key={viewProfile.userId} profile={viewProfile} editable={viewProfile.userId===userId} onClose={()=>setViewProfile(null)} onSave={saveProfile}/>}</div>;
}
