import {existsSync,readFileSync,writeFileSync} from 'node:fs';
const stage=process.argv[2];
if(!['staging','production'].includes(stage))throw Error('Choose staging or production');
const envFile=`cloudflare/environments/${stage}.json`;
const saved=existsSync(envFile)?JSON.parse(readFileSync(envFile,'utf8')):{};
if(!process.env.D1_DATABASE_ID && saved.database_id)process.env.D1_DATABASE_ID=saved.database_id;
const required=['CLOUDFLARE_ACCOUNT_ID','D1_DATABASE_ID','APP_ORIGIN','GOOGLE_CLIENT_ID'];
for(const name of required)if(!process.env[name])throw Error(`Missing ${name}`);
if(!/^[a-f0-9]{32}$/.test(process.env.CLOUDFLARE_ACCOUNT_ID))throw Error('Invalid account ID');
if(!/^[a-f0-9-]{36}$/.test(process.env.D1_DATABASE_ID)||process.env.D1_DATABASE_ID.startsWith('00000000-'))throw Error('Use the real D1 database ID');
const name=`tsuri-kiroku-${stage}`,origin=new URL(process.env.APP_ORIGIN);
if(origin.protocol!=='https:'||origin.origin!==process.env.APP_ORIGIN||!origin.hostname.startsWith(name+'.')||!origin.hostname.endsWith('.workers.dev'))throw Error('Use this environment’s exact workers.dev origin');
const config=JSON.parse(readFileSync('wrangler.jsonc','utf8'));
config.name=name;config.account_id=process.env.CLOUDFLARE_ACCOUNT_ID;
config.d1_databases=[{binding:'DB',database_name:name,database_id:process.env.D1_DATABASE_ID,migrations_dir:'drizzle'}];
config.r2_buckets=[{binding:'BUCKET',bucket_name:`tsuri-kiroku-photos-${stage}`}];
config.vars={APP_ORIGIN:origin.origin,GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID};
writeFileSync('wrangler.deploy.json',JSON.stringify(config,null,2)+'\n');
console.log(`Prepared ${stage} configuration (no secrets).`);
